[project]
name = ""
version = ""
description = ""
authors = [
    {name = "dev", email = "dev@gmail.com"},
]
dependencies = [
    "crawl4ai>=0.6.3"

]
requires-python = "==3.10.*"
license = {text = "MIT"}
[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

